<?php

namespace CovoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrajetRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends EntityRepository {

    public function findAllForSearch(string $q) {
        $qb = $this->createQueryBuilder('t')
            ->innerJoin('t.localisations', 'l');

        $qb->where('l.ville = :q')
            ->orWhere('l.adresse = :q')
            ->orWhere('l.codePostal = :q')
            ->setParameter('q', $q);

        return $qb->getQuery()->getResult();
    }
}
