<?php

namespace CovoiturageBundle\Repository;

/**
 * TrajetRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends AbstractRepository {

    /**
     * @param string $order
     * @param int $limit
     * @param int $offset
     * @return \Pagerfanta\Pagerfanta
     */
    public function findAllForPagination(string $order = 'asc', int $limit = 20, int $offset = 0) {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.id', $order);

        return $this->paginate($qb, $limit, $offset);
    }
    
    /**
     * @param string $q
     * @return array
     */
    public function findAllForSearch(string $q) {
        $qb = $this->createQueryBuilder('t')
            ->innerJoin('t.localisations', 'l');

        $qb->where('l.ville = :q')
            ->orWhere('l.adresse = :q')
            ->orWhere('l.codePostal = :q')
            ->setParameter('q', $q);

        return $qb->getQuery()->getResult();
    }
}
