covoiturage:
    resource: "@CovoiturageBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /users
    defaults:
        _format: json

app:
    resource: '@AppBundle/Controller/'
    type: annotation
