<?php
/**
 * Created by PhpStorm.
 * User: amacabr2
 * Date: 13/11/17
 * Time: 16:53
 */

namespace UserBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ForgotPasswordType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('password', PasswordType::class, [
                'label' => "Nouveau mot de passe",
                'attr' => array(
                    'class' => 'form-control ',
                    'value' => "",
                )
            ])
            ->add('password_confirmation', PasswordType::class, [
                'label' => "Confirmer mot de passe",
                'attr' => array(
                    'class' => 'form-control ',
                    'value' => "",
                )
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    public function getBlockPrefix() {
        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}